### ISSUE TITLE
Linting: Error when duplicate Container names

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-yaml#10]
The following should return a lint error. We should check for duplicate names in both the steps and the services section.

```
kind: pipeline
name: default

steps:
- name: build
  image: alpine

- name: build
  image: alpine
```
