### ISSUE TITLE
panic: nil environment variable, settings

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-yaml#13]
this can cause a panic, so we need to handle it in our codebase:

```
kind: pipeline
name: default
steps:
  - name: test
    image: clojure
    pull: always
    commands:
      - env
      - ./scripts/test.sh
    environment:
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      POSTGRES_PORT_5432_TCP_PORT: 5432
      REDIS_PORT_6379_TCP_ADDR: redis
      REDIS_PORT_6379_TCP_PORT: 6379
      LEIN_USERNAME:
      LEIN_PASSPHRASE:
```

I'm partial to failing the yaml parsing if nil with a useful error message, for example, `Nil or empty environment variables are not allowed`.
