### ISSUE TITLE
cpu resources are not compiled to json

### ISSUE THREAD

**Issue by zetaab** [drone/drone-yaml#16]
I am trying to compile following to json:

```
kind: pipeline
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi
```

the result is 
```
      "resources": {
        "limits": {
          "memory": 2147483648
        },
        "requests": {
          "memory": 1073741824
        }
      },
```
