### ISSUE TITLE
support yaml merge keys

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-yaml#43]
regression when we upgrade to go modules, we stopped using the fork of go-yaml that supported this syntax. Example:

```
---
build: &build
  image: meltwaterfoundation/drone-terraform:0.11.11
  secrets:
    - source: deploy_key
      target: deploy_key

pipeline:
  init:
    <<: *build
    commands:
      - echo yo

branches:
  - master
```

consider the following forks:
https://github.com/vinzenz/yaml/tree/fix-for-issue-91
https://github.com/buildkite/yaml

**Comment by bradrydzewski** [comment]
Good news, I am able to get merge key working with the 1.0 yaml file:

```
buildx: &buildx
  image: meltwaterfoundation/drone-terraform:0.11.11
  secrets:
    - source: deploy_key
      target: deploy_key

kind: pipeline
name: default

steps:
- name: foo
  <<: *buildx
  commands:
      - echo yo
```

Bad news, we were forced to use a new fork (from buildkite) because the old fork we were using does panics using the latest version of Go and also lacks support for multi-document yaml files. This is an unexpected setback. 

It is possible I can port the changes from `fix-for-issue-91` to the buildkite fork, and I will research doing so, however, I am not sure what sort of effort is involved yet :(

cc @jimsheldon
