### ISSUE TITLE
unit tests for conversion and escaping

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-yaml#44]
reported errors with the following pipeline:

```
pipeline:
  inspect:
    image: meltwaterfoundation/drone-git
    commands:
      - git --no-pager diff --name-only $(commit_range.sh) | grep \/
```

steps to reproduce:

1. save file to .drone.yml
2. run `drone convert --save`
3. run `drone exec`

oddly the following steps do not reproduce:

1. save file to .drone.yml
2. run `drone exec` (conversion handled implicitly)

**Comment by bradrydzewski** [comment]
@jimsheldon I have a local patch that generate the below yaml file. It will quote the string and prevents the extra escape. Can you confirm this doesn't break the command?

```
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: inspect
  pull: default
  image: "alpine:3.8"
  commands:
  - "- git --no-pager diff --name-only $(commit_range.sh) | grep /"
```

**Comment by bradrydzewski** [comment]
note to self, this needs to be fixed in the `isQuoted` function. The `\` character should generally be quoted in yaml, but not if it is already being used to escape a special character. See if we can re-use the yaml Escape function in the official Go library ...

**Comment by bradrydzewski** [comment]
good reference for escaping:
http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html

updated the code to not escape `|` or `>` unless these are the starting characters. This should fix the issues with the sample configuration file. However, we should note that escaping may still be imperfect which could impact any yaml file that is generated using `drone fmt`.

**Comment by jimsheldon** [comment]
I can confirm that this pipeline works fine under drone 1.1.0 (simplified the pipeline a bit)
```
pipeline:
  inspect:
    image: alpine:3.9
    commands:
      - "echo changed/directory | grep /"
    when:
      event: [ pull_request, push ]
```
Is that what you are asking?
