### ISSUE TITLE
improve pretty print escaping

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-yaml#45]
conversion of the following 0.8 yaml:

```
  job:
    image: my/image
    param: 'One: Two'
```

leads to an invalid yaml due to lack of escaping:

```
- name: job
  pull: default
  image: my/image
  settings:
    param: One: Two
```

my guess is that we need to add `:` to the following function to ensure values get quoted:
https://github.com/drone/drone-yaml/blob/master/yaml/pretty/util.go#L66
