### ISSUE TITLE
Missing env variables in automatic 0.5 -> 1.0 yml support (fallback)

### ISSUE THREAD

**Issue by strk** [drone/drone-yaml#46]
This yml: https://git.osgeo.org/gitea/geos/php-geos/src/tag/1.0.0/.drone.yml
Results in this error: https://dronie.osgeo.org/geos/php-geos/2/1/2

Note the empty elments in the printed PATH value

**Comment by tboerger** [comment]
You can see the test cases at https://github.com/drone/drone-yaml/blob/master/yaml/converter/legacy/internal/testdata/matrix_1.yml and https://github.com/drone/drone-yaml/blob/master/yaml/converter/legacy/internal/testdata/matrix_2.yml, these are working fine so far.

If you find an issue at https://github.com/drone/drone-yaml/blob/master/yaml/converter/legacy/internal/config.go#L90-L159 feel free to send a patch, after that drone-yaml could be updated with the next server release.

**Comment by strk** [comment]
The example file https://github.com/drone/drone-yaml/blob/master/yaml/converter/legacy/internal/testdata/matrix_2.yml is not using env variables, or doesn't look like (in the shell part...)

**Comment by strk** [comment]
I've given `drone convert` a try and it resulted in steps like this:
```
steps:
- name: build
  pull: always
  image: docker.kbt.io/php-geos/build-test:trisquel
  commands:
  - "export PATH=/opt/php-5.4.9/bin/:/opt/geos-3.4.3/bin/:${PATH}"
  - "echo ${PATH}"
  - php --version
  - /opt/php-7.1.0/bin/phpize
  - ./configure
  - make
  - make check
```

Why the quoting ?
