### ISSUE TITLE
Legacy converter should handle False settings

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-yaml#52]
the following 0.8 configuration file:

```
pipeline:
  mystep:
    auto_merge: "false"
...
```

produces the following (auto_merge is missing):

```
---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: mystep
  pull: if-not-exists
  image: foo
  settings:

...
```

the temporary workaround is to quote the value in the source yaml:

```
pipeline:
  mystep:
    auto_merge: "false"
...
```
